"""Minimal errno constants for moonpython stdlib."""

ENOENT = 2
ENOTDIR = 20
EBADF = 9
ECHILD = 10
ELOOP = 40
EEXIST = 17
EACCES = 13
EPERM = 1
EINVAL = 22
ENOSYS = 38
ENOTSUP = 95
ECONNRESET = 104
EAGAIN = 11
EWOULDBLOCK = 11
EINPROGRESS = 115
EALREADY = 114
ECONNREFUSED = 111
ENOTCONN = 107
EISCONN = 106
ESHUTDOWN = 108
ECONNABORTED = 103
EPIPE = 32

errorcode = {
    ENOENT: "ENOENT",
    ENOTDIR: "ENOTDIR",
    EBADF: "EBADF",
    ECHILD: "ECHILD",
    ELOOP: "ELOOP",
    EEXIST: "EEXIST",
    EACCES: "EACCES",
    EPERM: "EPERM",
    EINVAL: "EINVAL",
    ENOSYS: "ENOSYS",
    ENOTSUP: "ENOTSUP",
    ECONNRESET: "ECONNRESET",
    EAGAIN: "EAGAIN",
    EWOULDBLOCK: "EWOULDBLOCK",
    EINPROGRESS: "EINPROGRESS",
    EALREADY: "EALREADY",
    ECONNREFUSED: "ECONNREFUSED",
    ENOTCONN: "ENOTCONN",
    EISCONN: "EISCONN",
    ESHUTDOWN: "ESHUTDOWN",
    ECONNABORTED: "ECONNABORTED",
    EPIPE: "EPIPE",
}
